// @ts-nocheck -- skip type checking
import * as meta_0 from "../content/docs/meta.json?collection=meta"
import * as docs_14 from "../content/docs/hooks/use-auto-resize-textarea.mdx?collection=docs"
import * as docs_13 from "../content/docs/components/searchbars.mdx?collection=docs"
import * as docs_12 from "../content/docs/components/otp-inputs.mdx?collection=docs"
import * as docs_11 from "../content/docs/components/inputs.mdx?collection=docs"
import * as docs_10 from "../content/docs/components/dialogs.mdx?collection=docs"
import * as docs_9 from "../content/docs/components/checkboxes.mdx?collection=docs"
import * as docs_8 from "../content/docs/components/carousel.mdx?collection=docs"
import * as docs_7 from "../content/docs/components/cards.mdx?collection=docs"
import * as docs_6 from "../content/docs/components/breadcrumbs.mdx?collection=docs"
import * as docs_5 from "../content/docs/components/bentogrids.mdx?collection=docs"
import * as docs_4 from "../content/docs/components/avatars.mdx?collection=docs"
import * as docs_3 from "../content/docs/components/animated-text.mdx?collection=docs"
import * as docs_2 from "../content/docs/components/accordion.mdx?collection=docs"
import * as docs_1 from "../content/docs/blocks/ai-card-generation.mdx?collection=docs"
import * as docs_0 from "../content/docs/index.mdx?collection=docs"
import { _runtime } from "fumadocs-mdx/runtime/next"
import * as _source from "../source.config"
export const docs = _runtime.doc<typeof _source.docs>([{ info: {"path":"index.mdx","fullPath":"content/docs/index.mdx"}, data: docs_0 }, { info: {"path":"blocks/ai-card-generation.mdx","fullPath":"content/docs/blocks/ai-card-generation.mdx"}, data: docs_1 }, { info: {"path":"components/accordion.mdx","fullPath":"content/docs/components/accordion.mdx"}, data: docs_2 }, { info: {"path":"components/animated-text.mdx","fullPath":"content/docs/components/animated-text.mdx"}, data: docs_3 }, { info: {"path":"components/avatars.mdx","fullPath":"content/docs/components/avatars.mdx"}, data: docs_4 }, { info: {"path":"components/bentogrids.mdx","fullPath":"content/docs/components/bentogrids.mdx"}, data: docs_5 }, { info: {"path":"components/breadcrumbs.mdx","fullPath":"content/docs/components/breadcrumbs.mdx"}, data: docs_6 }, { info: {"path":"components/cards.mdx","fullPath":"content/docs/components/cards.mdx"}, data: docs_7 }, { info: {"path":"components/carousel.mdx","fullPath":"content/docs/components/carousel.mdx"}, data: docs_8 }, { info: {"path":"components/checkboxes.mdx","fullPath":"content/docs/components/checkboxes.mdx"}, data: docs_9 }, { info: {"path":"components/dialogs.mdx","fullPath":"content/docs/components/dialogs.mdx"}, data: docs_10 }, { info: {"path":"components/inputs.mdx","fullPath":"content/docs/components/inputs.mdx"}, data: docs_11 }, { info: {"path":"components/otp-inputs.mdx","fullPath":"content/docs/components/otp-inputs.mdx"}, data: docs_12 }, { info: {"path":"components/searchbars.mdx","fullPath":"content/docs/components/searchbars.mdx"}, data: docs_13 }, { info: {"path":"hooks/use-auto-resize-textarea.mdx","fullPath":"content/docs/hooks/use-auto-resize-textarea.mdx"}, data: docs_14 }]);
export const meta = _runtime.meta<typeof _source.meta>([{ info: {"path":"meta.json","fullPath":"content/docs/meta.json"}, data: meta_0 }]);