"use client";
import { cn } from "@/lib/utils";
import { AnimatePresence, motion } from "motion/react";
import { useState } from "react";

const mockData = {
    tabs: ["Overview", "Analytics", "Reports"],
    content: [
        "Your total revenue for this month is $12,450. This is a 20% increase compared to last month's performance.",
        "Traffic is up by 15%. Most of your users are visiting from mobile devices (65%) with an average session duration of 2m 30s.",
        "You have 3 unread reports generated by the system. The Q3 financial summary is ready for download."
    ],
}

const UnderlineTab = () => {
    const [activeTab, setActiveTab] = useState(0);

  return (
    <div className="flex flex-col gap-4 w-full max-w-md">
        <div className="relative flex w-full border-b border-neutral-200 dark:border-neutral-800">
            {mockData.tabs.map((tab, index) => {
                const isActive = activeTab === index;

                return (
                    <button 
                        key={index}
                        onClick={() => setActiveTab(index)}
                        className={cn(
                            "relative w-full px-2 text-sm font-medium rounded-md transition-colors duration-200",
                            isActive
                                ? "text-neutral-900 dark:text-neutral-100"
                                : "text-neutral-500 hover:text-neutral-700 dark:text-neutral-400 dark:hover:text-neutral-200"
                        )}
                    >
                        <span>{tab}</span>

                        {isActive && (
                            <motion.span
                                layoutId="underline-tab"
                                className="absolute bottom-0 left-0 right-0 h-0.5 bg-neutral-900 dark:bg-neutral-100 z-10"
                                transition={{ type: "spring", stiffness: 300, damping: 30 }}
                            />
                        )}
                    </button>
                )
            })}
        </div>

        <div className="min-h-[150px] p-4">
            <AnimatePresence mode="wait">
                <motion.div
                    key={activeTab}
                    initial={{ opacity: 0, y: 10, filter: "blur(4px)" }}
                    animate={{ opacity: 1, y: 0, filter: "blur(0px)" }}
                    exit={{ opacity: 0, y: -10, filter: "blur(4px)" }}
                    transition={{ duration: 0.3, ease: "easeOut" }}
                    className="text-sm leading-relaxed text-neutral-600 dark:text-neutral-300"
                >
                    { mockData.content[activeTab] }
                </motion.div>
            </AnimatePresence>
        </div>
    </div>
  )
}

export default UnderlineTab;
